### PR TITLE
Fix  #161

### LINKED ISSUE #161: Issue with shared react dependency
We have this error when using shared dependencies `react` + `react-dom`:
`Uncaught TypeError: application 'myRemoteApp' died in status LOADING_SOURCE_CODE: Cannot read properties of undefined (reading 'ReactCurrentOwner')`

This error is not happening if we removed shared from the option of the plugin. (But react is loaded two times)

### Versions

- originjs: 1.1.3
- node: 16.14

### Reproduction

We will create a reproduction as soon as possible but maybe we are doing something wrong with our config.
We don't see any exemple that use react on both side.

Config on vite (host)
```typescript
 federation({
      name: 'myApp',
      remotes:{
        myRemoteApp: {
          external: 'http://localhost:3001/remoteEntry.js',
          format: 'var',
        }
      },
      shared: {
        react: {
          version: '^17.0.1',
        },
        'react-dom': {
          version: '^17.0.1',
        }
      }
    }),
```

Config on Webpack (remote)
```javascript
  new ModuleFederationPlugin({
            name: 'myRemoteApp',
            filename: 'remoteEntry.js',
            exposes: {
                './App': './src/App',
            },
            shared: [
                {
                    ...deps,
                    react: {
                        singleton: true,
                        requiredVersion: deps.react,
                    },
                    'react-dom': {
                        singleton: true,
                        requiredVersion: deps['react-dom'],
                    },
                },
            ],
        }),
```

This Webpack configuration for the remote is perfectly working with an other Webpack config as host.

Thank you for your help.
We will try to provide reproduction as soon as possible

### PR DESCRIPTION
**Pull request by Timehello**
### Description

@ruleeeer Hi, I try to fix #161 via some modifies below:
1. In development mode, use rollup resolve function to get the shared module path first, and use the original way as fallback
2. Modify the getter of shared, if remote is from webpack, the getter will try to expose the content under the "default" field of an esm module, because webpack looks like didn't handle esm like module in share container( If not, please let me know :-) )

### Additional context

[reproduction](https://github.com/HeadFox/issue-161-vite-plugin-federation)
reproduct steps:
1. Serve the "webpack-remote-project"
2. Run dev command of "vite-host-project"

You will  see the remote module be not resolved

---

### What is the purpose of this pull request? 

- [x] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [ ] Read the [Contributing Guidelines](https://github.com/originjs/vite-plugin-federation/blob/main/CONTRIBUTING.md) and follow the [Commit Convention](https://github.com/originjs/vite-plugin-federation/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by ruleeeer** [comment]
@Timehello 
Hi, Sorry, I'll start reviewing PR later, I've been a little busy lately

**Comment by Timehello** [comment]
@ruleeeer ok, and I will try to build an ubuntu environment to fix the check later

**Comment by Timehello** [comment]
It seem that all checks have passed although I have done nothing.
I build an environment of ubuntu and test these cases, some are failed in jest e2e test, but it's a little weird that those faild cases are running well in brower

**Comment by ruleeeer** [comment]
> @ruleeeer Hi, It seems that all checks have passed although I have done nothing. I build an environment of ubuntu and test these cases, some are failed in jest e2e test, but it's a little weird that those faild cases are running well in brower

Sometimes the CI test will fail, most of the time I run it again and it works

**Comment by Timehello** [comment]
> @Timehello Hi,I have tried to use module.default to replace the module, which may be a problem in some libraries (may be element-plus), which is the reason why react in build mode has not been fixed, I had hoped that the problem would be solved if react was upgraded to ESM, but react to date But react is still a CJS library, I can try to merge into PR first, and then come back to observe the use of the upgrade

@ruleeeer Thanks for replying! I think it's webpack problem about handle esm in share container, if you provide a cjs module as share scope to remote module builded by webpack, the remote module runs well. But this is just my guess, and I'm also in checking if my guess is true.



> Regarding the changes in dev mode have you tested if they work? I tried to run the repository in Issue using your branch and it reports an error

Yes, I test it both in windows os and ubuntu, it runs well both in development and production mode. Could you please provide some screenshot about the error ?

**Comment by ruleeeer** [comment]
@Timehello  I'll merge into this PR and release a new version, then observe the community's reaction to the new version, React's issue are too many, it's time to let them reduce some

**Review by ruleeeer — APPROVED** [review]

**Comment by ruleeeer** [comment]
Thank you for your awesome contribution!

**Pull request merged**
