### PR TITLE
skip non existing dependency priority

### PR DESCRIPTION
**Pull request by zgid123**
This PR is about skip the non existing dependency priority.

For example, we have those packages' dependencies like this

```
axios: {},
react: {},
lodash: {},
my-package: { react: {}, lodash: {} },
```

Our `orderByDepCount` will be like this

```
orderByDepCount: [
  Map(3): { axios, react, lodash }, // those packages do not depend on any package
  undefined, // this is empty item because no package has `value.size` is 1
  Map(1): { my-package }, // package my-package depend on react and lodash, the value.size will be 2
]
```

Because there is no package's dependencies with size 1.

So we can filter the `orderByDepCount` element to remove undefined/empty item, or skip the empty item like this one

### CODE REVIEW

**Comment by zgid123** [comment]
This will fix issue #90

**Comment by ruleeeer** [comment]
First of all, thank you for PR,but I used your test case to reproduce the problem in serve mode because the shared name carries a '/'.
Thanks again for the test case and PR

**Comment by ruleeeer** [comment]
Please upgrade to version 1.0.5 and use the following configuration.
monoApp:
``` 
federation({
        name: 'monoApp',
        filename: 'remoteEntry.js',
        exposes: {
          './App': './src/App',
        },
        shared: {
          react: {
            eager: true,
            requiredVersion: pkg.dependencies.react,
          },
          'react-dom': {
            eager: true,
            import: false,
            requiredVersion: pkg.dependencies['react-dom'],
          },
          'react-router-dom': {
            eager: true,
            import: false,
            requiredVersion: pkg.dependencies['react-router-dom'],
          },
          '@chakra-ui/react': {},
          // '@emotion/react': '*',
          // '@emotion/styled': '*',
          // 'framer-motion': '*',
        },
      }),
```
*** 
superApp
```
federation({
        remotes: {
          mono: 'http://127.0.0.1:8000/assets/remoteEntry.js',
        },
        shared: {
          react: {
            eager: true,
            singleton: true,
            requiredVersion: pkg.dependencies.react,
          },
          'react-dom': {
            eager: true,
            singleton: true,
            requiredVersion: pkg.dependencies['react-dom'],
          },
          'react-router-dom': {
            eager: true,
            singleton: true,
            requiredVersion: pkg.dependencies['react-router-dom'],
          },
          '@chakra-ui/react': {},
        },
      }),
```

**Comment by ruleeeer** [comment]
However, the Vite DEV model of the test case is still unavailable. This is a problem that may be more troublesome, let me continue to handle it.

**Comment by zgid123** [comment]
Hi @ruleeeer, thanks for your rely, but the problem will occur when we have the dependency list like I mentioned.

For my test project, we should uncomment those lines in `vite.config.ts` of `monoApp`

```
'@emotion/react': '*',
'@emotion/styled': '*',
'framer-motion': '*',
```

So the value of `orderByDepCount` will look like this (I use console log)

```
[
  Map(1) { 'react' => Set(0) {} },
  Map(4) {
    'react-dom' => Set(1) { 'react' },
    'react-router-dom' => Set(1) { 'react' },
    '@emotion/react' => Set(1) { 'react' },
    'framer-motion' => Set(1) { 'react' }
  },
  Map(1) { '@emotion/styled' => Set(2) { 'react', '@emotion/react' } },
  <2 empty items>,
  Map(1) {
    '@chakra-ui/react' => Set(5) {
      'react',
      '@emotion/react',
      'react-dom',
      '@emotion/styled',
      'framer-motion'
    }
  }
]
```

As you can see, there are two empty items. Based on the other items, I assume those two empty items if have value should contain the element whose value should be a Set(3) and/or Set(4).

I already upgraded to latest version

```
"@originjs/vite-plugin-federation@^1.0.5":
  version "1.0.5"
  resolved "https://registry.yarnpkg.com/@originjs/vite-plugin-federation/-/vite-plugin-federation-1.0.5.tgz#22f949f7f3c1ce17923ade34789331a9e2b523e1"
  integrity sha512-4h7LvWVY7WE8oT+XATBCpLyws7roNugu6OE1FTsCP3oTGU5VWiPguTM/PywlQJmy6/FD/RFw+9lcgkIOK90lug==
  dependencies:
    estree-walker "^1.0.1"
    magic-string "^0.25.7"
```

**Comment by zgid123** [comment]
because we init the `orderByDepCount` like this

```ts
      const orderByDepCount: Map<string, Set<string>>[] = []
      depInShared.forEach((value, key) => {
        if (!orderByDepCount[value.size]) {
          orderByDepCount[value.size] = new Map()
        }
        orderByDepCount[value.size].set(key, value)
      })
```

The `depInShared` does not contain any element whose value.size is 3 or 4, that's why we faced this issue

**Comment by zgid123** [comment]
> First of all, thank you for PR,but I used your test case to reproduce the problem in serve mode because the shared name carries a '/'.
> Thanks again for the test case and PR

Just wanna confirm, with your latest commit, I can now use chakra-ui, thanks for your effort. And now I don't need those comment packages anymore.

But thanks to that, we found out the current issue

**Comment by ruleeeer** [comment]
It seems that you can change this, I changed a little bit.Thank you for your contribution

**Review by ruleeeer — APPROVED** [review]

**Pull request merged**
