### PR TITLE
docs(examples): add webpack-host

### PR DESCRIPTION
**Pull request by tzachbon**
### Description

Introduces a straightforward example demonstrating using Webpack as a host with the vite-plugin-federation. Following this example, users can better understand and utilize the plugin to integrate vite apps into Webpack applications. 

TODO:
- [x] Fix kill ports script port

### What is the purpose of this pull request? 

- [x] Documentation update

### Before submitting the PR, please make sure you do the following

- [x] Read the [Code of Conduct](https://github.com/originjs/vite-plugin-federation/blob/main/CODE_OF_CONDUCT.md) and follow the [Commit Convention](https://github.com/originjs/vite-plugin-federation/blob/main/.github/commit-convention.md) guidelines.
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by ruleeeer** [comment]
Could you fix the failed CI test?

**Comment by ruleeeer** [comment]
It should be noted that if you use `*dev&serve*` to name the test file, this will lead to the use of two modes of testing(dev and build&serve).

**Comment by tzachbon** [comment]
> Could you fix the failed CI test?

I am not sure why it is failing since it works locally 🤔. I did update the file name to only have "serve".

**Comment by ygj6** [comment]
> > Could you fix the failed CI test?
> 
> I am not sure why it is failing since it works locally 🤔. I did update the file name to only have "serve".

Try to use port 5000 instead of 5001
```
Error: page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:5000/
```

**Review by ruleeeer — APPROVED** [review]

**Pull request merged**
