### PR TITLE
feat(dev): added content hash for exposed modules

### PR DESCRIPTION
**Pull request by MarkusJLechner**
### Description

Here is the PR for the issue https://github.com/originjs/vite-plugin-federation/issues/197
All exposed imports are without an content hash, caching in the browser is not possible. With this PR, exposed files get the content hash suffix and look like this: `__federation_expose_V1BaseHeaderLine_46c3cd.js`

fixes https://github.com/originjs/vite-plugin-federation/issues/197

ps: **Contributing Guidelines** link is outdated

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following 

- [x] Read the [Contributing Guidelines](https://github.com/originjs/vite-plugin-federation/blob/main/CONTRIBUTING.md) and follow the [Commit Convention](https://github.com/originjs/vite-plugin-federation/blob/main/.github/commit-convention.md).
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [ ] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [ ] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by ruleeeer** [comment]
thanks for ps:Contributing Guidelines link is outdated,I will try to add one later

**Comment by MarkusJLechner** [comment]
I had some trouble when running the pre-commit hook in connection to pnpm. Also when looking on the CI failures, they are connected to `pnpm run build`, may you have more context to these errors?

**Comment by MarkusJLechner** [comment]
Hashing the exposed files would be a really nice addition to this plugin, I hope you'll find time to check this :coffee:

**Comment by ruleeeer** [comment]
It could be a CI problem, because I tried locally without reporting an error

**Comment by ruleeeer** [comment]
@MarkusJLechner Is it possible to rebase the upstream code and resubmit it? There was a problem with the previous CI, which I fixed yesterday, but the code for your PR still has the wrong CI version

**Comment by MarkusJLechner** [comment]
just updated upstream :+1:

**Comment by ruleeeer** [comment]
It still doesn't seem to pass CI, I'll pull your code and run it on my computer later to see what the problem is

**Comment by ruleeeer** [comment]
The problem has been fixed, the key to the problem is if the user fills in an abbreviated exposure formation path, for example 
``` js
federation({
      filename: 'remoteEntry.js',
      exposes: {
        '. /Button': 'src/button'
      }
    })
```
 which will call in
``` js
export function createContentHash(path: string): string {
  const content = readFileSync(path, { encoding: 'utf-8' })
  return createHash('md5').update(content).digest('hex').toString().slice(0, 8)
}
```
This code reports an error, because `src/button` is not a legal path, its real path should be `. /src/button.js`, so I prioritized the `rollup.resolve()` method to get the real path, and then used `createContentHash()` to fix the problem, thanks for your contribution to this feature!

**Review by ruleeeer — APPROVED** [review]

**Pull request merged**
