### PR TITLE
Feat: dynamic loading of remote support & test demo

### PR DESCRIPTION
**Pull request by zhtyytg**
### Description

link to https://github.com/originjs/vite-plugin-federation/pull/475#issue-1836152853

### Additional context

~Note!!!: It still have some problem when using the plugin [vite-plugin-top-level-await](https://github.com/Menci/vite-plugin-top-level-await) in remote component. The module cannot be found after first loading（I guess the top-level-await makes it async, so it will be found after a promise resolved, but I did not find the position to proof this.）~
No problem when I us the static import again... My mistake

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Read the [Code of Conduct](https://github.com/originjs/vite-plugin-federation/blob/main/CODE_OF_CONDUCT.md) and follow the [Commit Convention](https://github.com/originjs/vite-plugin-federation/blob/main/.github/commit-convention.md) guidelines.
- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.

### CODE REVIEW

**Comment by zhtyytg** [comment]
Avoid simultaneous import remote components both using import('module/component') and import { __federation_method_xxx } from 'virtual:__federation__' in one file.
The import('module/component') will be translated automatically.
The plugin will automatically import { __federation_method_xxx } from 'virtual:__federation__' at same time.
I haven't figured out how to fix it yet.

**Comment by diogoparente** [comment]
Finally a PR exporting `__federation_method_setRemote` and allowing the plugin to dynamically load a remote.
Thank you so much for your contribution, I hope this gets merged soon.

This will solve the issue at #193

**Comment by fgatti675** [comment]
Awesome! Thanks @zhtyytg for this PR!

**Comment by diogoparente** [comment]
Do we foresee this PR getting merged anytime soon?

**Comment by diogoparente** [comment]
> 

Totally understandable. It's just that once something like this gets added, the plugin will take off 🚀 
I'm quite new to the plugin, so I'm missing context. Do you have any documentation on the topic so maybe I can lend a hand?

Thank you for your efforts 👏

**Comment by diogoparente** [comment]
> > Do we foresee this PR getting merged anytime soon? @zhtyytg
> 
> There is a better way to dynamic import remote. But I'm so busy these days. walk AST as the plugin used to, just gave a virtual regexp name maybe better?

> 

Totally understandable. It's just that once something like this gets added, the plugin will take off 🚀 
I'm quite new to the plugin, so I'm missing context. Do you have any documentation on the topic so maybe I can lend a hand?

Thank you for your efforts 👏

**Comment by ruleeeer** [comment]
I noticed that all the tests have unfortunately failed. Are you still planning to submit the pull request? If so, I would suggest setting the status of the pull request to "draft" to prevent any unintended actions by the maintenance personnel. This would allow you to continue working on the necessary improvements without affecting the current state of the project.

**Comment by AsuraKev** [comment]
will this PR allow us to define dynamic remote url to support multiple environment? 

image

**Review by ruleeeer — APPROVED** [review]
LGTM

**Comment by deanshubOpenweb** [comment]
any timeline on releasing? really need this feature

**Comment by dipiash** [comment]
Hi!

Let me know please when it will be released?

**Comment by AsuraKev** [comment]
2025

**Comment by ruleeeer** [comment]
> any timeline on releasing? really need this feature

Version 1.3.1 has been released.

**Comment by JessYan0913** [comment]
> > any timeline on releasing? really need this feature有发布时间表吗？确实需要这个功能
> 
> Version 1.3.1 has been released.1.3.1版本已经发布。

我是用的v1.3.3，我发现还是无法动态导入远程模块啊

**Pull request merged**
