### PR TITLE
[WIP] add remotesMap and __federation_method_getRemote for dynamic import

### PR DESCRIPTION
**Pull request by DileSoft**
So you can do this in code:

```
window.remotesMap[this.props.schema.name] = {url:window._customComponent,format:'esm',from:'vite'};
const component = await window.__federation_method_getRemote(this.props.schema.name, './Components');
```

### CODE REVIEW

**Comment by DileSoft** [comment]
It also need to check if this variables was used in code for activate federation. But I don't know how to detect it.

**Comment by DileSoft** [comment]
Found how add check.

**Comment by DileSoft** [comment]
Added dynamicRemotes option for detect if app use dynamic remotes.

**Comment by flyfishzy** [comment]
Can you add some test cases or examples?

**Comment by DileSoft** [comment]
I will test it on my projects and show how it works.

**Comment by ruleeeer** [comment]
@DileSoft Is this PR still valid? You have changed more than expected

**Comment by ruleeeer** [comment]
@DileSoft Is this PR still valid? You have changed more than expected

**Comment by DileSoft** [comment]
I need dynamic remotes for project on that I work, so I made fork of your project. I plan to test it on my projects and propose to merge it to your plugin after that. I don't know how do it right.

**Comment by AndreiSoroka** [comment]
maybe you would like to create an alpha version
like vite-plugin-federation@1.1.7-alpha.1

**Comment by ruleeeer** [comment]
It looks like there will be no new developments in this PR for a while, I will close it and feel free to open it if there are new developments

**Pull request closed without merging**
