### PR TITLE
fix semver source

### PR DESCRIPTION
**Pull request by zgid123**
Because we put the built source of `semver` to the project. There is a problem when using `satisfies` method.

image

This is because of two things

- from `constructor` of `class Range`
```js
range instanceof Range$a
/*
 * range is a string, so this will cause error 
 * don't know why if I installed semver directly, I didn't face this issue
*/
```

- from `parseRange` of `class Range`
```js
map(comp => new Comparator$3(comp, this.options));
/*
 *  it must be Comparator$2
 * Comparator$3 is null even we are using var to define that variable, don't know why no hoisting here
*/
```

```ts
// const id = await this.resolveId(arr[0])
const id = (await this.resolve(arr[0]))?.id // resolveId is deperated, so I change this to resolve
```

```sh
The "this.resolveId" plugin context function used by plugin originjs:federation is deprecated. The "this.resolve" plugin context function should be used instead.
```

### CODE REVIEW

**Comment by zgid123** [comment]
I do think we should import or copy folder class/functions of semver into this project instead of copy the built source?

**Comment by ruleeeer** [comment]
Maybe we need to change to try to implement a semver ourselves just like webpack, which provides a lite version of semver
1, because it's too wasteful to bring in a whole library, we only need one of the methods
2, there may be some technical problems with introducing a native semver, because semver is a commonjs format, it may need to be translated to ESM to be parsed by rollup, and then by rollup to the user's fomat
So it would be nice if we could provide an ESM format tiny with just one  satisfy method

**Comment by ruleeeer** [comment]
this is webpack tiny semver.js 
https://github.com/webpack/webpack/blob/main/lib/util/semver.js

**Comment by zgid123** [comment]
yup, I think so, lemme try to implement it

**Comment by zgid123** [comment]
I just updated the code, but still, I cannot build any example project. For example, when building `remote-esm` of `simple-react-esm`, I will face this error

```
│ src/index.js → dist...
│ babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
│ [!] TypeError: (0 , plugin_virtual_1.default) is not a function
│ TypeError: (0 , plugin_virtual_1.default) is not a function
│     at registerPlugins (/Users/alpha/Alpha/open-sources/community/typescript/vite-plugin-federation/packages/lib/dist/index.js:45:51)
│     at Object.options (/Users/alpha/Alpha/open-sources/community/typescript/vite-plugin-federation/packages/lib/dist/index.js:58:17)
│     at /Users/alpha/Alpha/open-sources/community/typescript/vite-plugin-federation/node_modules/.pnpm/rollup@2.60.2/node_modules/rollup/dist/shared/rollup.js:23473:43
│     at getInputOptions (/Users/alpha/Alpha/open-sources/community/typescript/vite-plugin-federation/node_modules/.pnpm/rollup@2.60.2/node_modules/rollup/dist/shared/rollup.js:23466:61)
│     at rollupInternal (/Users/alpha/Alpha/open-sources/community/typescript/vite-plugin-federation/node_modules/.pnpm/rollup@2.60.2/node_modules/rollup/dist/shared/rollup.js:23413:72)
│     at build (/Users/alpha/Alpha/open-sources/community/typescript/vite-plugin-federation/node_modules/.pnpm/rollup@2.60.2/node_modules/rollup/dist/bin/rollup:1546:20)
│     at runRollup (/Users/alpha/Alpha/open-sources/community/typescript/vite-plugin-federation/node_modules/.pnpm/rollup@2.60.2/node_modules/rollup/dist/bin/rollup:1730:21)
```

maybe we cannot import and run the code directly right? Is there any way to compile the code before using it as `__federation_lib_semver`?

Also, I need more test cases for prerelease version and other versions too. It seems my test cases are poor, and my project does not have `prerelease package`, so I still not done that yet.

Also for the jest, I will check it again because while running the test case alone, it will be passed, but to run full test, it throws error and I still not fix it

**Comment by ruleeeer** [comment]
The imported code should be compiled, because it will eventually run in the user's project, not in vite-plugin-federation, so importing the source code directly may not work

**Comment by ruleeeer** [comment]
But if we insert the compiled code directly, once we modify semver.ts, this means we also have to modify the inserted compiled code, and it's too much of a hassle to modify it every time

**Comment by ruleeeer** [comment]
I came up with a way to accomplish this, even if it's not so elegant
Add a build of the semver to rollup.config.js in vite-plugin-federation, and read the contents of the semver file to complete the replacement when it runs in the client project, so that even if we change the source code of the semver, the template will change along with it,let me try changing this part, it should only take a relatively small number of changes to complete

**Review by ruleeeer — APPROVED** [review]

**Pull request merged**
