### PR TITLE
test: add env variable demo

### PR DESCRIPTION
**Pull request by genffy**
update env variable demo on `vue3-advanced-demo`

### CODE REVIEW

**Comment by ruleeeer** [comment]
Can you solve the CI failure problem first?

**Comment by genffy** [comment]
> Can you solve the CI failure problem first?

the error log's show failed at 'Install deps' step, can u go to Actions panel and rerun it?

**Comment by ruleeeer** [comment]
I tried to re-run it and it still doesn't pass CI, please pay attention to this line of error message
`ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with packages/examples/vue3-advanced-demo/router-host/package.json`

**Review by ruleeeer — APPROVED** [review]

**Comment by ruleeeer** [comment]
thanks for your pr!

**Pull request merged**
