### PR TITLE
fix: #147 task2

### PR DESCRIPTION
**Pull request by Timehello**
add generateBundle hook to sharedPlugin, to transform the shared function of remotes' dependencies through find out the related chunks and transform them with logic like what renderChunk hook do
@ruleeeer

### CODE REVIEW

**Review by ruleeeer — CHANGES_REQUESTED** [review]
Nice, your code can solve the original bug, but there is still a problem that needs attention .Try not to change the code in the `generateBundle` hook, this is because some JS encryption and obfuscation libraries will obfuscate or encrypt the code in the `renderChunk` hook, and the `generatorBundle` runs after the `renderChunk`, this causes the code output by the plugin to be unobfuscated and unencrypted. You need to output the code in the `renderChunk` hook to complete, and you can use the [this.getModuleInfo()](https://rollupjs.org/guide/en/#thisgetmoduleinfo) hook to get the information you need

**Comment by Timehello** [comment]
@ruleeeer thanks for your tips! I'll try to do what you said soon ;-)

**Comment by Timehello** [comment]
@ruleeeer hi
I try to refactor the logic of this part. add buildEnd hook(ensure that all modules' info are parsed by rollup) to collect the modules which import shared lib, and in the renderChunk hook, transform the chunks which contain the modules collected before

**Comment by ruleeeer** [comment]
@Timehello thank you very much , I will be the first to review when I have free time

**Review by ruleeeer — APPROVED** [review]

**Comment by ruleeeer** [comment]
thanks for your nice PR

**Pull request merged**
