### PR TITLE
feat: add content hash for shared libraries

### PR DESCRIPTION
**Pull request by MauriceAyasse**
### Description

This fixes the problem described in #482.

Shared library build files now receive a content hash in their file name (e.g., __federation_shared_react-000ea6e2.js). With this change, it becomes easier to implement a caching solution in the browser. Consequently, the browser can respond to changes in shared libraries when their content changes.

Caching should now be possible; otherwise, this would have a performance impact. Theotther JavaScript chunks already have hashes, so it is only reasonable to add them here as well.

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### CODE REVIEW

**Comment by chris-muller** [comment]
I couldn't find any information on how this repo accepts contributions. This PR would fix an issue we had in production, is there anything I can do to help get this merged?

@ygj6  @flyfishzy @PeterAlfredLee

**Comment by MauriceAyasse** [comment]
There was a change needes so this PR were still in the draft status.

I changed the parameters of `this.emitFile()` to only use the name. The file resolution should work with the `import.meta.ROLLUP_FILE_URL_referenceId` variable, so a custom file name should not be required. As a result, the hash algorithm and resolution of Rollup.js will be used on the shared libraries.

**Review by ruleeeer — APPROVED** [review]
LGTM

**Comment by Sultanyaron** [comment]
@ruleeeer Hi, any plans to release this?

**Comment by sethsandaru** [comment]
curios for the release date too @ruleeeer , thanks

**Comment by ruleeeer** [comment]
@Sultanyaron @sethsandaru 
1.3.2 has been released

**Comment by linux-nerd** [comment]
Is there a way to opt out of the hash in the file name?

**Pull request merged**
