### PR TITLE
fix semver and add pre-release checker

### PR DESCRIPTION
**Pull request by zgid123**
fix semver logic when checking `x range` (`*` and `x`) and add pre-release logic checker

### CODE REVIEW

**Comment by zgid123** [comment]
image
can I get the full errors of the CI for windows-latest? Because I only see like this one, so I don't know what the issue is 😂

**Comment by zgid123** [comment]
@ruleeeer can you help?

**Comment by ruleeeer** [comment]
don't worry, sometimes I will fail the test on windows, most of these problems will succeed after re-running

**Comment by ruleeeer** [comment]
hahah,it seems to have succeeded

**Comment by zgid123** [comment]
finally 😂😂

**Comment by ruleeeer** [comment]
I don’t know what this is because of it, but when I run it again, there is a high probability that it will succeed.

**Pull request merged**
